In [ ]:
# Christopher Chong, StudentID: 260976714
# this code is for running experiments on CNN and LSTM

# using keras for model implementation

# load in datasets
!pip install datasets
from datasets import load_dataset
dataset = load_dataset("app_reviews")


# convert to pandas dataframe
import pandas as pd
df = dataset['train'].to_pandas()
df.head()



dataset = df[["review", "star"]]



In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
import tensorflow as tf
import numpy as np

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
# preprocessing for the data
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
def review_preprocess(text):
    text = text.lower()
    text = word_tokenize(text)
    lemmatize = WordNetLemmatizer()
    text = [lemmatize.lemmatize(word) for word in text]
    stop_words = set(stopwords.words('english'))
    text = [word for word in text if word not in stop_words]
    return text

dataset['review'] = dataset['review'].apply(lambda x: review_preprocess(x))
dataset['review'] = dataset['review'].astype(str)
dataset

review  star
34430   ['love', '!', '!', '!', '!', 'far', 'best', 'r...     5
170339                                     ['liked', '👍']     4
116866  ['nice', 'ui', 'doe', "n't", 'work', 'utorrent...     3
76784                            ['u3fjahat', 'u3fjahat']     5
246010                                     ['nice', 'ok']     1
...                                                   ...   ...
141200  ['?', '?', 'app', 'ha', 'updated', 'long', 'ti...     3
10708                      ['best', 'best', 'app', 'coc']     5
84491   ['publish', 'publish', 'thing', 'like', 'text'...     2
148526                                  ['عالیه', 'good']     5
26522   ['excellent', 'tool', 'maximum', 'battery', 'l...     5

[57613 rows x 2 columns]

In [ ]:
text_data = dataset['review'].values.tolist()

labels = np.array(dataset['star'])

# turn labels into data neural network ccan use
labels = tf.keras.utils.to_categorical(labels, 6, dtype="float32")


In [ ]:
import time

from keras.models import Sequential

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

from keras.optimizers import RMSprop,Adam
from keras import layers


In [ ]:
# DOUBLE CHECKED

max_num_words = 2000

# converting text data into data usable by the neural network using official keras tensorflow documentation:
# https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text/Tokenizer

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(text_data)

sequences = tokenizer.texts_to_sequences(text_data) #encodes the data used to train from texts into usable sequences
sentences = pad_sequences(sequences) # ensures all sequences in the list gets the same length

In [ ]:
#Splitting the data, # DOUBLE CHECKED

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(sentences, labels, test_size=0.25, random_state=0)


EXPERIMENT 1 - CNN EPOCH = 10




In [ ]:
# DOUBLE CHECKED
epochs = 10
batch_size = 64


CNN_model = Sequential()
CNN_model.add(layers.Embedding(max_num_words, 50))
CNN_model.add(layers.Conv1D(5, 4, activation='relu'))
CNN_model.add(layers.MaxPooling1D(10))


CNN_model.add(layers.Conv1D(10, 8, activation='relu'))
CNN_model.add(layers.GlobalMaxPooling1D())

CNN_model.add(layers.Dense(6,activation='softmax'))
CNN_model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
start = time.time()
CNN_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()


test_loss, test_acc = CNN_model.evaluate(X_test, y_test, verbose=2)


print(f"Training time: {stop - start}s")

print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)

Epoch 1/10
3376/3376 [==============================] - 63s 19ms/step - loss: 1.1206 - acc: 0.6191 - val_loss: 1.0662 - val_acc: 0.6331
Epoch 2/10
3376/3376 [==============================] - 59s 18ms/step - loss: 1.0520 - acc: 0.6394 - val_loss: 1.0458 - val_acc: 0.6415
Epoch 3/10
3376/3376 [==============================] - 61s 18ms/step - loss: 1.0407 - acc: 0.6434 - val_loss: 1.0414 - val_acc: 0.6420
Epoch 4/10
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0341 - acc: 0.6447 - val_loss: 1.0367 - val_acc: 0.6437
Epoch 5/10
3376/3376 [==============================] - 59s 17ms/step - loss: 1.0301 - acc: 0.6454 - val_loss: 1.0550 - val_acc: 0.6353
Epoch 6/10
3376/3376 [==============================] - 64s 19ms/step - loss: 1.0275 - acc: 0.6461 - val_loss: 1.0313 - val_acc: 0.6446
Epoch 7/10
3376/3376 [==============================] - 60s 18ms/step - loss: 1.0255 - acc: 0.6467 - val_loss: 1.0309 - val_acc: 0.6432
Epoch 8/10
3376/3376 [==========================

EXPERIMENT 2 - CNN EPOCH = 20


In [ ]:

epochs = 20
batch_size = 64


CNN_model = Sequential()
CNN_model.add(layers.Embedding(max_num_words, 50))
CNN_model.add(layers.Conv1D(5, 4, activation='relu'))
CNN_model.add(layers.MaxPooling1D(10))


CNN_model.add(layers.Conv1D(10, 8, activation='relu'))
CNN_model.add(layers.GlobalMaxPooling1D())

CNN_model.add(layers.Dense(6,activation='softmax'))
CNN_model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
start = time.time()
CNN_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()


test_loss, test_acc = CNN_model.evaluate(X_test, y_test, verbose=2)


print(f"Training time: {stop - start}s")

print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)

Epoch 1/20
3376/3376 [==============================] - 60s 18ms/step - loss: 1.1071 - acc: 0.6236 - val_loss: 1.0723 - val_acc: 0.6307
Epoch 2/20
3376/3376 [==============================] - 63s 19ms/step - loss: 1.0519 - acc: 0.6383 - val_loss: 1.0460 - val_acc: 0.6382
Epoch 3/20
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0384 - acc: 0.6419 - val_loss: 1.0377 - val_acc: 0.6398
Epoch 4/20
3376/3376 [==============================] - 67s 20ms/step - loss: 1.0305 - acc: 0.6443 - val_loss: 1.0326 - val_acc: 0.6431
Epoch 5/20
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0270 - acc: 0.6454 - val_loss: 1.0289 - val_acc: 0.6428
Epoch 6/20
3376/3376 [==============================] - 59s 17ms/step - loss: 1.0245 - acc: 0.6465 - val_loss: 1.0279 - val_acc: 0.6443
Epoch 7/20
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0228 - acc: 0.6467 - val_loss: 1.0253 - val_acc: 0.6444
Epoch 8/20
3376/3376 [==========================

EXPERIMENT 3 - CNN EPOCH = 30


In [ ]:
# DOUBLE CHECKED

epochs = 30
batch_size = 64


CNN_model = Sequential()
CNN_model.add(layers.Embedding(max_num_words, 50))
CNN_model.add(layers.Conv1D(5, 4, activation='relu'))
CNN_model.add(layers.MaxPooling1D(10))


CNN_model.add(layers.Conv1D(10, 8, activation='relu'))
CNN_model.add(layers.GlobalMaxPooling1D())

CNN_model.add(layers.Dense(6,activation='softmax'))
CNN_model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
start = time.time()
CNN_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()


test_loss, test_acc = CNN_model.evaluate(X_test, y_test, verbose=2)


print(f"Training time: {stop - start}s")

print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)

Epoch 1/30
3376/3376 [==============================] - 59s 17ms/step - loss: 1.1180 - acc: 0.6183 - val_loss: 1.0688 - val_acc: 0.6309
Epoch 2/30
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0536 - acc: 0.6363 - val_loss: 1.0482 - val_acc: 0.6382
Epoch 3/30
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0378 - acc: 0.6414 - val_loss: 1.0389 - val_acc: 0.6394
Epoch 4/30
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0308 - acc: 0.6437 - val_loss: 1.0358 - val_acc: 0.6408
Epoch 5/30
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0270 - acc: 0.6455 - val_loss: 1.0308 - val_acc: 0.6416
Epoch 6/30
3376/3376 [==============================] - 57s 17ms/step - loss: 1.0242 - acc: 0.6464 - val_loss: 1.0291 - val_acc: 0.6424
Epoch 7/30
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0214 - acc: 0.6478 - val_loss: 1.0304 - val_acc: 0.6424
Epoch 8/30
3376/3376 [==========================

Batch Size


EXPERIMENT 4 - CNN BATCHSIZE = 32


In [ ]:
# DOUBLE CHECKED

epochs = 20
batch_size = 32


CNN_model = Sequential()
CNN_model.add(layers.Embedding(max_num_words, 50))
CNN_model.add(layers.Conv1D(5, 4, activation='relu'))
CNN_model.add(layers.MaxPooling1D(10))


CNN_model.add(layers.Conv1D(10, 8, activation='relu'))
CNN_model.add(layers.GlobalMaxPooling1D())

CNN_model.add(layers.Dense(6,activation='softmax'))
CNN_model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
start = time.time()
CNN_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size )
stop = time.time()


test_loss, test_acc = CNN_model.evaluate(X_test, y_test, verbose=2)


print(f"Training time: {stop - start}s")

print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)

Epoch 1/20
6752/6752 [==============================] - 75s 11ms/step - loss: 1.1430 - acc: 0.6289 - val_loss: 1.0676 - val_acc: 0.6361
Epoch 2/20
6752/6752 [==============================] - 69s 10ms/step - loss: 1.0489 - acc: 0.6418 - val_loss: 1.0475 - val_acc: 0.6412
Epoch 3/20
6752/6752 [==============================] - 73s 11ms/step - loss: 1.0374 - acc: 0.6442 - val_loss: 1.0389 - val_acc: 0.6434
Epoch 4/20
6752/6752 [==============================] - 71s 11ms/step - loss: 1.0322 - acc: 0.6454 - val_loss: 1.0345 - val_acc: 0.6437
Epoch 5/20
6752/6752 [==============================] - 73s 11ms/step - loss: 1.0282 - acc: 0.6459 - val_loss: 1.0314 - val_acc: 0.6428
Epoch 6/20
6752/6752 [==============================] - 69s 10ms/step - loss: 1.0254 - acc: 0.6461 - val_loss: 1.0286 - val_acc: 0.6449
Epoch 7/20
6752/6752 [==============================] - 75s 11ms/step - loss: 1.0237 - acc: 0.6467 - val_loss: 1.0270 - val_acc: 0.6445
Epoch 8/20
6752/6752 [==========================

EXPERIMENT 5 - CNN BATCHSIZE = 64


In [ ]:
# DOUBLE CHECKED

epochs = 20
batch_size = 64


CNN_model = Sequential()
CNN_model.add(layers.Embedding(max_num_words, 50))
CNN_model.add(layers.Conv1D(5, 4, activation='relu'))
CNN_model.add(layers.MaxPooling1D(10))


CNN_model.add(layers.Conv1D(10, 8, activation='relu'))
CNN_model.add(layers.GlobalMaxPooling1D())

CNN_model.add(layers.Dense(6,activation='softmax'))
CNN_model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
start = time.time()
CNN_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()


test_loss, test_acc = CNN_model.evaluate(X_test, y_test, verbose=2)


print(f"Training time: {stop - start}s")

print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)

Epoch 1/20
3376/3376 [==============================] - 58s 17ms/step - loss: 1.1117 - acc: 0.6202 - val_loss: 1.0669 - val_acc: 0.6315
Epoch 2/20
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0510 - acc: 0.6385 - val_loss: 1.0488 - val_acc: 0.6393
Epoch 3/20
3376/3376 [==============================] - 59s 18ms/step - loss: 1.0379 - acc: 0.6431 - val_loss: 1.0382 - val_acc: 0.6416
Epoch 4/20
3376/3376 [==============================] - 57s 17ms/step - loss: 1.0315 - acc: 0.6450 - val_loss: 1.0369 - val_acc: 0.6429
Epoch 5/20
3376/3376 [==============================] - 60s 18ms/step - loss: 1.0278 - acc: 0.6460 - val_loss: 1.0451 - val_acc: 0.6388
Epoch 6/20
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0256 - acc: 0.6462 - val_loss: 1.0296 - val_acc: 0.6450
Epoch 7/20
3376/3376 [==============================] - 59s 17ms/step - loss: 1.0235 - acc: 0.6474 - val_loss: 1.0275 - val_acc: 0.6442
Epoch 8/20
3376/3376 [==========================

EXPERIMENT 6 - CNN BATCHSIZE = 128


In [ ]:
# DOUBLE CHECKED

epochs = 20
batch_size = 128


CNN_model = Sequential()
CNN_model.add(layers.Embedding(max_num_words, 50))
CNN_model.add(layers.Conv1D(5, 4, activation='relu'))
CNN_model.add(layers.MaxPooling1D(10))


CNN_model.add(layers.Conv1D(10, 8, activation='relu'))
CNN_model.add(layers.GlobalMaxPooling1D())

CNN_model.add(layers.Dense(6,activation='softmax'))
CNN_model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
start = time.time()
CNN_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size )
stop = time.time()


test_loss, test_acc = CNN_model.evaluate(X_test, y_test, verbose=2)


print(f"Training time: {stop - start}s")

print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)

Epoch 1/20
1688/1688 [==============================] - 57s 33ms/step - loss: 1.1223 - acc: 0.6162 - val_loss: 1.0831 - val_acc: 0.6247
Epoch 2/20
1688/1688 [==============================] - 54s 32ms/step - loss: 1.0680 - acc: 0.6327 - val_loss: 1.0639 - val_acc: 0.6324
Epoch 3/20
1688/1688 [==============================] - 55s 32ms/step - loss: 1.0530 - acc: 0.6382 - val_loss: 1.0490 - val_acc: 0.6377
Epoch 4/20
1688/1688 [==============================] - 55s 33ms/step - loss: 1.0397 - acc: 0.6429 - val_loss: 1.0406 - val_acc: 0.6412
Epoch 5/20
1688/1688 [==============================] - 55s 33ms/step - loss: 1.0314 - acc: 0.6458 - val_loss: 1.0340 - val_acc: 0.6430
Epoch 6/20
1688/1688 [==============================] - 56s 33ms/step - loss: 1.0267 - acc: 0.6467 - val_loss: 1.0306 - val_acc: 0.6429
Epoch 7/20
1688/1688 [==============================] - 57s 34ms/step - loss: 1.0234 - acc: 0.6475 - val_loss: 1.0294 - val_acc: 0.6442
Epoch 8/20
1688/1688 [==========================

Vocab Size


EXPERIMENT 7 - CNN max_vocab_size = 1000


In [ ]:
# DOUBLE CHECKED

max_num_words = 1000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)

sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)

epochs = 20
batch_size = 64


CNN_model = Sequential()
CNN_model.add(layers.Embedding(max_num_words, 50))
CNN_model.add(layers.Conv1D(5, 4, activation='relu'))
CNN_model.add(layers.MaxPooling1D(10))


CNN_model.add(layers.Conv1D(10, 8, activation='relu'))
CNN_model.add(layers.GlobalMaxPooling1D())

CNN_model.add(layers.Dense(6,activation='softmax'))
CNN_model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
start = time.time()
CNN_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size )
stop = time.time()


test_loss, test_acc = CNN_model.evaluate(X_test, y_test, verbose=2)


print(f"Training time: {stop - start}s")

print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)

[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/20
3376/3376 [==============================] - 60s 18ms/step - loss: 1.1132 - acc: 0.6205 - val_loss: 1.0716 - val_acc: 0.6315
Epoch 2/20
3376/3376 [==============================] - 65s 19ms/step - loss: 1.0563 - acc: 0.6368 - val_loss: 1.0539 - val_acc: 0.6359
Epoch 3/20
3376/3376 [==============================] - 59s 18ms/step - loss: 1.0447 - acc: 0.6401 - val_loss: 1.0462 - val_acc: 0.6373
Epoch 4/20
3376/3376 [==============================] - 65s 19ms/step - loss: 1.0388 - acc: 0.6408 - val_loss: 1.0401 - val_acc: 0.6392
Epoch 5/20
3376/3376 [==============================] - 64s 19ms/step - loss: 1.0350 - acc: 0.6418 - val_loss: 1.0357 - val_acc: 0.6413
Epoch 6/20
3376/3376 [==============================] - 57s 17ms/step - loss: 1.0321 - acc: 0.6434 - val_loss: 1.0402 - val_acc: 0.6389
Ep

EXPERIMENT 8 - CNN max_vocab_size = 2000


In [ ]:
# DOUBLE CHECKED

max_num_words = 2000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)

sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)

epochs = 20
batch_size = 64


CNN_model = Sequential()
CNN_model.add(layers.Embedding(max_num_words, 50))
CNN_model.add(layers.Conv1D(5, 4, activation='relu'))
CNN_model.add(layers.MaxPooling1D(10))


CNN_model.add(layers.Conv1D(10, 8, activation='relu'))
CNN_model.add(layers.GlobalMaxPooling1D())

CNN_model.add(layers.Dense(6,activation='softmax'))
CNN_model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
start = time.time()
CNN_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size )
stop = time.time()


test_loss, test_acc = CNN_model.evaluate(X_test, y_test, verbose=2)


print(f"Training time: {stop - start}s")

print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)

[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/20
3376/3376 [==============================] - 58s 17ms/step - loss: 1.1002 - acc: 0.6251 - val_loss: 1.0665 - val_acc: 0.6332
Epoch 2/20
3376/3376 [==============================] - 57s 17ms/step - loss: 1.0549 - acc: 0.6379 - val_loss: 1.0567 - val_acc: 0.6353
Epoch 3/20
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0443 - acc: 0.6410 - val_loss: 1.0465 - val_acc: 0.6376
Epoch 4/20
3376/3376 [==============================] - 56s 17ms/step - loss: 1.0375 - acc: 0.6421 - val_loss: 1.0409 - val_acc: 0.6396
Epoch 5/20
3376/3376 [==============================] - 59s 17ms/step - loss: 1.0314 - acc: 0.6448 - val_loss: 1.0320 - val_acc: 0.6432
Epoch 6/20
3376/3376 [==============================] - 57s 17ms/step - loss: 1.0264 - acc: 0.6463 - val_loss: 1.0288 - val_acc: 0.6441
Ep

EXPERIMENT 9 - CNN max_vocab_size = 3000


In [ ]:
# DOUBLE CHECKED

max_num_words = 3000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)

sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)


epochs = 20
batch_size = 64


CNN_model = Sequential()
CNN_model.add(layers.Embedding(max_num_words, 50))
CNN_model.add(layers.Conv1D(5, 4, activation='relu'))
CNN_model.add(layers.MaxPooling1D(10))


CNN_model.add(layers.Conv1D(10, 8, activation='relu'))
CNN_model.add(layers.GlobalMaxPooling1D())

CNN_model.add(layers.Dense(6,activation='softmax'))
CNN_model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
start = time.time()
CNN_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size )
stop = time.time()


test_loss, test_acc = CNN_model.evaluate(X_test, y_test, verbose=2)


print(f"Training time: {stop - start}s")

print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)

[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/20
3376/3376 [==============================] - 59s 17ms/step - loss: 1.1032 - acc: 0.6241 - val_loss: 1.0621 - val_acc: 0.6325
Epoch 2/20
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0490 - acc: 0.6382 - val_loss: 1.0543 - val_acc: 0.6366
Epoch 3/20
3376/3376 [==============================] - 63s 19ms/step - loss: 1.0364 - acc: 0.6418 - val_loss: 1.0363 - val_acc: 0.6413
Epoch 4/20
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0289 - acc: 0.6442 - val_loss: 1.0300 - val_acc: 0.6427
Epoch 5/20
3376/3376 [==============================] - 62s 18ms/step - loss: 1.0242 - acc: 0.6457 - val_loss: 1.0297 - val_acc: 0.6434
Epoch 6/20
3376/3376 [==============================] - 58s 17ms/step - loss: 1.0208 - acc: 0.6467 - val_loss: 1.0283 - val_acc: 0.6433
Ep

LSTM Model Experiments
Epoch

EXPERIMENT 1 - LSTM epoch = 10  


In [ ]:
# DOUBLE CHECKED

max_num_words = 2000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)

sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)






LSTM_model = Sequential()
LSTM_model.add(layers.Embedding(max_num_words, 50))
LSTM_model.add(layers.LSTM(10))
LSTM_model.add(layers.Dense(6,activation='softmax'))


epochs = 10
batch_size = 64

LSTM_model.compile(optimizer='rmsprop',loss='categorical_crossentropy', metrics=['accuracy'])
#Implementing model checkpoins to save the best metric and do not lose it on training.
start = time.time()
LSTM_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()

test_loss, test_acc = LSTM_model.evaluate(X_test, y_test, verbose=2)

print(f"Training time: {stop - start}s")
print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)


[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/10
3376/3376 [==============================] - 279s 82ms/step - loss: 1.1311 - accuracy: 0.6119 - val_loss: 1.0961 - val_accuracy: 0.6173
Epoch 2/10
3376/3376 [==============================] - 272s 81ms/step - loss: 1.0850 - accuracy: 0.6239 - val_loss: 1.0689 - val_accuracy: 0.6304
Epoch 3/10
3376/3376 [==============================] - 273s 81ms/step - loss: 1.0556 - accuracy: 0.6329 - val_loss: 1.0704 - val_accuracy: 0.6354
Epoch 4/10
3376/3376 [==============================] - 271s 80ms/step - loss: 1.0342 - accuracy: 0.6391 - val_loss: 1.0229 - val_accuracy: 0.6423
Epoch 5/10
3376/3376 [==============================] - 274s 81ms/step - loss: 1.0151 - accuracy: 0.6446 - val_loss: 1.0108 - val_accuracy: 0.6442
Epoch 6/10
3376/3376 [==============================] - 274s 81ms/step - loss: 1.00

EXPERIMENT 2 - LSTM epoch = 20  


In [ ]:
# DOUBLE CHECKED

max_num_words = 2000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)

sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)






LSTM_model = Sequential()
LSTM_model.add(layers.Embedding(max_num_words, 50))
LSTM_model.add(layers.LSTM(10))
LSTM_model.add(layers.Dense(6,activation='softmax'))


epochs = 20
batch_size = 64

LSTM_model.compile(optimizer='rmsprop',loss='categorical_crossentropy', metrics=['accuracy'])
#Implementing model checkpoins to save the best metric and do not lose it on training.
start = time.time()
LSTM_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()

test_loss, test_acc = LSTM_model.evaluate(X_test, y_test, verbose=2)

print(f"Training time: {stop - start}s")
print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)


[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/20
3376/3376 [==============================] - 277s 81ms/step - loss: 1.1312 - accuracy: 0.6115 - val_loss: 1.1002 - val_accuracy: 0.6162
Epoch 2/20
3376/3376 [==============================] - 280s 83ms/step - loss: 1.0874 - accuracy: 0.6238 - val_loss: 1.0690 - val_accuracy: 0.6297
Epoch 3/20
3376/3376 [==============================] - 274s 81ms/step - loss: 1.0576 - accuracy: 0.6341 - val_loss: 1.0441 - val_accuracy: 0.6388
Epoch 4/20
3376/3376 [==============================] - 275s 81ms/step - loss: 1.0344 - accuracy: 0.6410 - val_loss: 1.0276 - val_accuracy: 0.6435
Epoch 5/20
3376/3376 [==============================] - 273s 81ms/step - loss: 1.0182 - accuracy: 0.6459 - val_loss: 1.0081 - val_accuracy: 0.6461
Epoch 6/20
3376/3376 [==============================] - 279s 83ms/step - loss: 1.00

EXPERIMENT 3 - LSTM epoch = 30  


In [ ]:
# DOUBLE CHECKED

max_num_words = 2000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)

sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)






LSTM_model = Sequential()
LSTM_model.add(layers.Embedding(max_num_words, 50))
LSTM_model.add(layers.LSTM(10))
LSTM_model.add(layers.Dense(6,activation='softmax'))


epochs = 30
batch_size = 64

LSTM_model.compile(optimizer='rmsprop',loss='categorical_crossentropy', metrics=['accuracy'])
#Implementing model checkpoins to save the best metric and do not lose it on training.
start = time.time()
LSTM_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()

test_loss, test_acc = LSTM_model.evaluate(X_test, y_test, verbose=2) # verbose shows number of epochs in training

print(f"Training time: {stop - start}s")
print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)


[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/30
3376/3376 [==============================] - 283s 83ms/step - loss: 1.1351 - accuracy: 0.6114 - val_loss: 1.1103 - val_accuracy: 0.6109
Epoch 2/30
3376/3376 [==============================] - 279s 83ms/step - loss: 1.0974 - accuracy: 0.6215 - val_loss: 1.0915 - val_accuracy: 0.6223
Epoch 3/30
3376/3376 [==============================] - 278s 82ms/step - loss: 1.0752 - accuracy: 0.6279 - val_loss: 1.0747 - val_accuracy: 0.6264
Epoch 4/30
3376/3376 [==============================] - 281s 83ms/step - loss: 1.0535 - accuracy: 0.6337 - val_loss: 1.0405 - val_accuracy: 0.6363
Epoch 5/30
3376/3376 [==============================] - 276s 82ms/step - loss: 1.0287 - accuracy: 0.6412 - val_loss: 1.0247 - val_accuracy: 0.6386
Epoch 6/30
3376/3376 [==============================] - 279s 83ms/step - loss: 1.01

Max Vocab

EXPERIMENT 4 - LSTM max_vocab_size = 1000

In [ ]:
# DOUBLE CHECKED

max_num_words = 1000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)

sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)






LSTM_model = Sequential()
LSTM_model.add(layers.Embedding(max_num_words, 50))
LSTM_model.add(layers.LSTM(10))
LSTM_model.add(layers.Dense(6,activation='softmax'))


epochs = 20
batch_size = 64

LSTM_model.compile(optimizer='rmsprop',loss='categorical_crossentropy', metrics=['accuracy'])
#Implementing model checkpoins to save the best metric and do not lose it on training.
start = time.time()
LSTM_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()

test_loss, test_acc = LSTM_model.evaluate(X_test, y_test, verbose=2)

print(f"Training time: {stop - start}s")
print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)


[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/20
3376/3376 [==============================] - 281s 82ms/step - loss: 1.1279 - accuracy: 0.6133 - val_loss: 1.1206 - val_accuracy: 0.6197
Epoch 2/20
3376/3376 [==============================] - 277s 82ms/step - loss: 1.0884 - accuracy: 0.6258 - val_loss: 1.0809 - val_accuracy: 0.6246
Epoch 3/20
3376/3376 [==============================] - 277s 82ms/step - loss: 1.0629 - accuracy: 0.6335 - val_loss: 1.0526 - val_accuracy: 0.6346
Epoch 4/20
3376/3376 [==============================] - 282s 83ms/step - loss: 1.0415 - accuracy: 0.6386 - val_loss: 1.0492 - val_accuracy: 0.6318
Epoch 5/20
3376/3376 [==============================] - 280s 83ms/step - loss: 1.0271 - accuracy: 0.6426 - val_loss: 1.0252 - val_accuracy: 0.6415
Epoch 6/20
3376/3376 [==============================] - 277s 82ms/step - loss: 1.01

EXPERIMENT 5 - LSTM max_vocab_size = 2000

In [ ]:
# DOUBLE CHECKED

max_num_words = 2000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)
sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)






LSTM_model = Sequential()
LSTM_model.add(layers.Embedding(max_num_words, 50))
LSTM_model.add(layers.LSTM(10))
LSTM_model.add(layers.Dense(6,activation='softmax'))


epochs = 20
batch_size = 64

LSTM_model.compile(optimizer='rmsprop',loss='categorical_crossentropy', metrics=['accuracy'])
#Implementing model checkpoins to save the best metric and do not lose it on training.
start = time.time()
LSTM_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()

test_loss, test_acc = LSTM_model.evaluate(X_test, y_test, verbose=2)

print(f"Training time: {stop - start}s")
print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)


[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/20
3376/3376 [==============================] - 285s 83ms/step - loss: 1.1348 - accuracy: 0.6094 - val_loss: 1.1160 - val_accuracy: 0.6070
Epoch 2/20
3376/3376 [==============================] - 282s 84ms/step - loss: 1.1026 - accuracy: 0.6184 - val_loss: 1.0961 - val_accuracy: 0.6178
Epoch 3/20
3376/3376 [==============================] - 284s 84ms/step - loss: 1.0853 - accuracy: 0.6244 - val_loss: 1.0732 - val_accuracy: 0.6266
Epoch 4/20
3376/3376 [==============================] - 285s 84ms/step - loss: 1.0709 - accuracy: 0.6293 - val_loss: 1.0666 - val_accuracy: 0.6278
Epoch 5/20
3376/3376 [==============================] - 283s 84ms/step - loss: 1.0573 - accuracy: 0.6323 - val_loss: 1.0480 - val_accuracy: 0.6318
Epoch 6/20
3376/3376 [==============================] - 284s 84ms/step - loss: 1.04

EXPERIMENT 6 - LSTM max_vocab_size = 3000

In [ ]:
# DOUBLE CHECKED

max_num_words = 3000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)

sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)






LSTM_model = Sequential()
LSTM_model.add(layers.Embedding(max_num_words, 50))
LSTM_model.add(layers.LSTM(10))
LSTM_model.add(layers.Dense(6,activation='softmax'))


epochs = 20
batch_size = 64

LSTM_model.compile(optimizer='rmsprop',loss='categorical_crossentropy', metrics=['accuracy'])
#Implementing model checkpoins to save the best metric and do not lose it on training.
start = time.time()
LSTM_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()

test_loss, test_acc = LSTM_model.evaluate(X_test, y_test, verbose=2)

print(f"Training time: {stop - start}s")
print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)


[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/20
3376/3376 [==============================] - 285s 84ms/step - loss: 1.1344 - accuracy: 0.6125 - val_loss: 1.1168 - val_accuracy: 0.6160
Epoch 2/20
3376/3376 [==============================] - 285s 84ms/step - loss: 1.0968 - accuracy: 0.6230 - val_loss: 1.0969 - val_accuracy: 0.6248
Epoch 3/20
3376/3376 [==============================] - 285s 84ms/step - loss: 1.0785 - accuracy: 0.6273 - val_loss: 1.0710 - val_accuracy: 0.6276
Epoch 4/20
3376/3376 [==============================] - 282s 84ms/step - loss: 1.0539 - accuracy: 0.6341 - val_loss: 1.0494 - val_accuracy: 0.6334
Epoch 5/20
3376/3376 [==============================] - 287s 85ms/step - loss: 1.0353 - accuracy: 0.6381 - val_loss: 1.0343 - val_accuracy: 0.6337
Epoch 6/20
3376/3376 [==============================] - 283s 84ms/step - loss: 1.02

Batch Size


EXPERIMENT 7 - LSTM batch_size = 32

In [ ]:
# DOUBLE CHECKED

max_num_words = 2000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)

sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)






LSTM_model = Sequential()
LSTM_model.add(layers.Embedding(max_num_words, 50))
LSTM_model.add(layers.LSTM(10))
LSTM_model.add(layers.Dense(6,activation='softmax'))


epochs = 20
batch_size = 32

LSTM_model.compile(optimizer='rmsprop',loss='categorical_crossentropy', metrics=['accuracy'])
#Implementing model checkpoins to save the best metric and do not lose it on training.
start = time.time()
LSTM_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()

test_loss, test_acc = LSTM_model.evaluate(X_test, y_test, verbose=2)

print(f"Training time: {stop - start}s")
print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)


[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/20
6752/6752 [==============================] - 501s 74ms/step - loss: 1.1163 - accuracy: 0.6144 - val_loss: 1.0819 - val_accuracy: 0.6243
Epoch 2/20
6752/6752 [==============================] - 515s 76ms/step - loss: 1.0732 - accuracy: 0.6291 - val_loss: 1.0630 - val_accuracy: 0.6316
Epoch 3/20
6752/6752 [==============================] - 505s 75ms/step - loss: 1.0526 - accuracy: 0.6350 - val_loss: 1.0634 - val_accuracy: 0.6356
Epoch 4/20
6752/6752 [==============================] - 505s 75ms/step - loss: 1.0324 - accuracy: 0.6405 - val_loss: 1.0223 - val_accuracy: 0.6399
Epoch 5/20
6752/6752 [==============================] - 519s 77ms/step - loss: 1.0147 - accuracy: 0.6460 - val_loss: 1.0069 - val_accuracy: 0.6447
Epoch 6/20
6752/6752 [==============================] - 513s 76ms/step - loss: 1.00

EXPERIMENT 8 - LSTM batch_size = 64

In [ ]:
# DOUBLE CHECKED

max_num_words = 2000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)

sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)







LSTM_model = Sequential()
LSTM_model.add(layers.Embedding(max_num_words, 50))
LSTM_model.add(layers.LSTM(10))
LSTM_model.add(layers.Dense(6,activation='softmax'))


epochs = 20
batch_size = 64

LSTM_model.compile(optimizer='rmsprop',loss='categorical_crossentropy', metrics=['accuracy'])
#Implementing model checkpoins to save the best metric and do not lose it on training.
start = time.time()
LSTM_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()

test_loss, test_acc = LSTM_model.evaluate(X_test, y_test, verbose=2)

print(f"Training time: {stop - start}s")
print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)


[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/20
3376/3376 [==============================] - 284s 83ms/step - loss: 1.1320 - accuracy: 0.6103 - val_loss: 1.1058 - val_accuracy: 0.6097
Epoch 2/20
3376/3376 [==============================] - 282s 83ms/step - loss: 1.0956 - accuracy: 0.6195 - val_loss: 1.0827 - val_accuracy: 0.6234
Epoch 3/20
3376/3376 [==============================] - 280s 83ms/step - loss: 1.0712 - accuracy: 0.6274 - val_loss: 1.0684 - val_accuracy: 0.6322
Epoch 4/20
3376/3376 [==============================] - 277s 82ms/step - loss: 1.0396 - accuracy: 0.6388 - val_loss: 1.0423 - val_accuracy: 0.6391
Epoch 5/20
3376/3376 [==============================] - 279s 83ms/step - loss: 1.0224 - accuracy: 0.6443 - val_loss: 1.0156 - val_accuracy: 0.6433
Epoch 6/20
3376/3376 [==============================] - 280s 83ms/step - loss: 1.01

EXPERIMENT 9 - LSTM batch_size = 128

In [ ]:
# DOUBLE CHECKED

max_num_words = 2000

tokenizer = Tokenizer(num_words=max_num_words)
tokenizer.fit_on_texts(data)
sequences = tokenizer.texts_to_sequences(data)
sentences = pad_sequences(sequences)

X_train, X_test, y_train, y_test = train_test_split(sentences,labels, test_size = 0.25, random_state=0)






LSTM_model = Sequential()
LSTM_model.add(layers.Embedding(max_num_words, 50))
LSTM_model.add(layers.LSTM(10))
LSTM_model.add(layers.Dense(6,activation='softmax'))


epochs = 20
batch_size = 128

LSTM_model.compile(optimizer='rmsprop',loss='categorical_crossentropy', metrics=['accuracy'])
#Implementing model checkpoins to save the best metric and do not lose it on training.
start = time.time()
LSTM_model.fit(X_train, y_train, epochs= epochs,batch_size = batch_size)
stop = time.time()

test_loss, test_acc = LSTM_model.evaluate(X_test, y_test, verbose=2)

print(f"Training time: {stop - start}s")
print("Maximum number of words in tokenizer: ", max_num_words)
print("Number of Epochs for Training: ", epochs)
print("Batch Size: ", batch_size)
print('Model loss: ',test_loss)
print('Model accuracy: ',test_acc)


[[22  6  3 ... 19 13  9]
 [ 0  0  0 ...  8 14  1]
 [ 0  0  0 ...  7 22  6]
 ...
 [ 0  0  0 ...  3  5 10]
 [ 0  0  0 ...  1  2 14]
 [ 5 14  1 ...  3  3 10]]
216048 72017 216048 72017
Epoch 1/20
1688/1688 [==============================] - 172s 101ms/step - loss: 1.1396 - accuracy: 0.6122 - val_loss: 1.1016 - val_accuracy: 0.6228
Epoch 2/20
1688/1688 [==============================] - 162s 96ms/step - loss: 1.0920 - accuracy: 0.6248 - val_loss: 1.0835 - val_accuracy: 0.6274
Epoch 3/20
1688/1688 [==============================] - 170s 101ms/step - loss: 1.0741 - accuracy: 0.6291 - val_loss: 1.0671 - val_accuracy: 0.6311
Epoch 4/20
1688/1688 [==============================] - 162s 96ms/step - loss: 1.0559 - accuracy: 0.6345 - val_loss: 1.0509 - val_accuracy: 0.6356
Epoch 5/20
1688/1688 [==============================] - 162s 96ms/step - loss: 1.0403 - accuracy: 0.6388 - val_loss: 1.0317 - val_accuracy: 0.6401
Epoch 6/20
1688/1688 [==============================] - 163s 96ms/step - loss: 1.